FROM openjdk:22-jdk-slim
ARG project
COPY ./webapp/target/webapp-1.0-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java -jar -Dspring.profiles.active=prod -DACCESS_KEY=$ACCESS_KEY -DSECRET_ACCESS_KEY=$SECRET_ACCESS_KEY -DSESSION_TOKEN=$SESSION_TOKEN -DMONGO_USERNAME=$MONGO_USERNAME -DMONGO_PASSWORD=$MONGO_PASSWORD webapp-1.0-SNAPSHOT.jar"]