### inserts a new customer

POST {{host}}/api/insert
Content-Type: application/json
Accept: application/json

{
  "name": "Davide",
  "age": 32,
  "favouriteDestinations": {
    "destinations": [
      {
        "city": "Longone"
      }
    ]
  }
}

### find by id

GET {{host}}/api/findById?id=b5a1dc98-e5a9-41e8-9041-09876e83742c
Content-Type: application/json
Accept: application/json

### find all with a given name

GET {{host}}/api/findAll?name=Davide
Content-Type: application/json
Accept: application/json

### remove customer

POST {{host}}/api/remove/c0efd46b-183b-4341-ba72-010f911e5f79
Content-Type: application/json
Accept: application/json

### update destination

PUT {{host}}/api/update-destination/b5970bf9-873e-4c0f-b782-cd12d1d9ca39
Content-Type: application/json
Accept: application/json

{
  "old": "Erba",
  "new": "Chiasso"
}

### add destination

PUT {{host}}/api/add-destination/68518f4b-d8e8-4bae-a062-d2a65830152e
Content-Type: application/json
Accept: application/json

{
  "destination": "Lugano"
}

### remove destination

PUT {{host}}/api/remove-destination/89b4803b-afd8-46fb-9d9d-6300a9e75105
Content-Type: application/json
Accept: application/json

{
  "destination": "Como"
}

### retrieve translations

GET {{host}}/api/translations/en
Content-Type: application/json
Accept: application/json

### sends message through websocket

POST {{host}}/api/send
Content-Type: application/json
Accept: application/json

{
  "message": "What's up bro??"
}