### inserts a new customer

POST {{host}}/insert
Content-Type: application/json
Accept: application/json

{
    "name": "Stefania",
    "age": 32,
    "favouriteDestinations": {
        "destinations": [
            {
                "city": "Rochester"
            }
        ]
    }
}

### find by name

GET {{host}}/find?name=Stefania
Content-Type: application/json
Accept: application/json

### find by id

GET {{host}}/findById?id=38883420-6d47-410d-a892-d3c64c659f1e
Content-Type: application/json
Accept: application/json

### add destination

PUT {{host}}/add-destination/Stefania
Content-Type: application/json
Accept: application/json

{
  "destination": "Chicago"
}

### remove destination

PUT {{host}}/remove-destination/Davide
Content-Type: application/json
Accept: application/json

{
  "destination": "Milan"
}

### retrieve all users

GET {{host}}/retrieveUsers
Content-Type: application/json
Accept: application/json

### retrieve translations

GET {{host}}/translations/en
Content-Type: application/json
Accept: application/json

### sends message through websocket

POST {{host}}/send
Content-Type: application/json
Accept: application/json

{
  "message": "Hey there!!!"
}