### inserts a new customer

POST {{host}}/insert
Content-Type: application/json
Accept: application/json

{
  "name": "Karissa",
  "age": 31,
  "favouriteDestinations": {
    "destinations": [
      {
        "city": "Rochester"
      },
      {
        "city": "Richmond"
      }
    ]
  }
}

### remove customer

POST {{host}}/remove/b2ab9ad2-b739-4ba1-bb42-fd5c35ccf638
Content-Type: application/json
Accept: application/json

### find by name

GET {{host}}/find?name=Karissa
Content-Type: application/json
Accept: application/json

### find by id

GET {{host}}/findById?id=1234
Content-Type: application/json
Accept: application/json

### add destination

PUT {{host}}/add-destination/1234
Content-Type: application/json
Accept: application/json

{
  "destination": "Pavia"
}

### remove destination

PUT {{host}}/remove-destination/2
Content-Type: application/json
Accept: application/json

{
  "destination": "London"
}

### update destination

PUT {{host}}/update-destination/2
Content-Type: application/json
Accept: application/json

{
  "old": "Milan",
  "new": "Usmate Velate"
}

### retrieve all users

GET {{host}}/retrieveUsers
Content-Type: application/json
Accept: application/json

### retrieve translations

GET {{host}}/translations/en
Content-Type: application/json
Accept: application/json

### sends message through websocket

POST {{host}}/send
Content-Type: application/json
Accept: application/json

{
  "message": "What's up bro??"
}