services:
  app:
    image: davide92/spring-example2
    container_name: app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    restart:
      always
  mongo:
    image: mongo:4.4.18   # 4.4.18 is the last working version for raspberryPI (ARM64 bit)..
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - spring-example2-data-db:/data/db
      - spring-example2-data-db-prod:/Databases/production

volumes:
  spring-example2-data-db:
    driver: local
  spring-example2-data-db-prod:
    driver: local
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: unless-stopped
#    ports:
#      - "8081:8081"
#    links:
#      - mongo
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_SERVER: mongo
