services:
  app:
    image: davide92/spring-example2
    container_name: app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    restart:
      always
    environment:
      MONGO_USERNAME: root      #env var in your OS
      MONGO_PASSWORD: password  #env var in your OS
  mongo:
    image: mongo:4.4.18   # 4.4.18 is the last working version for raspberryPI (ARM64 bit)..
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - spring-example2-data-db:/data/db
      - spring-example2-data-db-prod:/Databases/production

volumes:
  spring-example2-data-db:
    driver: local
  spring-example2-data-db-prod:
    driver: local