server:
  servlet:
    context-path: /api

aws:
  accessKey: ${ACCESS_KEY}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  sessionToken: ${SESSION_TOKEN}
  bucketName: s3-bucket-example-1234599

mongo:
  url: mongodb://root:password@localhost:27017/?authSource=admin

spring:
  graphql:
    graphiql:
      enabled:
        true