server:
  servlet:
    context-path: /api

mongo:
  url: mongodb://root:password@mongo:27017/customers?authSource=admin

aws:
  accessKey: ${ACCESS_KEY}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  bucketName: s3-bucket-example-1234599