server:
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mongo:
  baseUrl: localhost:27017/?authSource=admin
  username: root
  password: password

enabledDB: mongo

aws:
  accessKey: ${ACCESS_KEY}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  sessionToken: ${SESSION_TOKEN}
  bucketName: images.davidebotti.com