server:
  servlet:
    context-path: /api

aws:
  accessKey: ${ACCESS_KEY}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  sessionToken: ${SESSION_TOKEN}
  bucketName: images.davidebotti.com

mongo:
  url: localhost:27017/?authSource=admin
  username: root
  password: password

#    mongodb://root:password@localhost:27017/?authSource=admin

enabledDB: mongo

spring:
  graphql:
    graphiql:
      enabled:
        true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB