server:
  servlet:
    context-path: /api

mongo:
  url: mongodb://root:password@mongo:27017/customers?authSource=admin

aws:
  accessKey: AKIASNM5FAX7AYSSAZ5O
  secretAccessKey: 6db8HPHxTt/p9hlFQhIn1utwazq69qhuRFr9JtLy
  bucketName: s3-bucket-example-1234599