server:
  servlet:
    context-path: /api

aws:
  accessKey: ${ACCESS_KEY}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  sessionToken: ${SESSION_TOKEN}
  bucketName: images.davidebotti.com

mongo:
  host: localhost
  username: root
  password: password
  port: 27017

enabledDB: mongo

spring:
  graphql:
    graphiql:
      enabled:
        true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB